steps:
  - label: ':docker: Test Docker'
    commands:
      - echo "--- Hello World"
      - sfdx -v
      - sfdx plugins
    plugins:
      - docker#v3.5.0:
          image: "dxatscale/sfpowerscripts:latest"
          mount-ssh-agent: false
          shell:
            - '/bin/bash'
            - '-e'
            - '-c'
